services:
  postgres:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
    ports:
      - "54321:5432"
    volumes:
      - ./data:/data
      - ./test:/test
    cpus: 2.0
    mem_limit: 4g
